### ISSUE TITLE
Mirrors on Kodi downloads, wrong city for me

### ISSUE THREAD

**Issue by orfeous1** [etix/mirrorbits#102]
Hi!
The nearest server mirror is complete wrong reported for me.
It tells me this.

"You are connecting with IP address 85.224.73.X, which belongs to autonomous system Telenor Norge AS (ASN2119)."
"We believe you are near Gothenburg in Sweden and have selected mirrors based on this."
Opposite side in Sweden.. far away.

But in fact im in the same city as the server here in Umeå at ACC mirror.
Whys that? My ISP is Telenor.

**Comment by chewitt** [comment]
It sounds like the GeoIP database has innacurate info on your location, which could be for a bunch of reasons outside both your and Team Kodi's control. It is what it is, but most mirrors are web browsabe so you can always go direct to othe mirror in the future to get files.

**Comment by I-Cat** [comment]
no it is a team Kodi secret

**Comment by orfeous1** [comment]
My location is now properly shown! Correct country and city! But now all Sweden's mirrors are gone.
And all nearest. The system tells me that Russia is the most near mirror.
Why is that? What happend to all scandinavian mirrors that was on the list before?

**Comment by orfeous1** [comment]
Now back to not show the correct city. It shows Storuman and that im ~700km away from the server but its not.
Its just a couple of kilometers.

Im located in Umeå and "Academic" are also located here in Umeå.
![mirror](https://user-images.githubusercontent.com/22922189/122468859-878e8e00-cfbc-11eb-8ff7-85a6cc5549cc.png)


I will attach a screenshot with mirrorbits.

**Comment by orfeous1** [comment]
GeoIP's database is now updated.
Ive contacted them about the info.
When i search for the ip it reports correct city now.

So now it seems that the issue is on mirrorbits.

**Comment by jbkempf** [comment]
Seems not a MB issue
