### ISSUE TITLE
Add support for If-Modified-Since

### ISSUE THREAD

**Issue by lazka** [etix/mirrorbits#115]
We mirror some files which get synced by clients regularly (using curl internally). mirrorbits will respond to these requests by redirecting to the best mirror and the mirror will then return 304 because the file hasn't changed.

Since mirrorbits already knows the mtime of the files it could in theory handle `If-Modified-Since` and return 304 itself.

**Comment by elboulangero** [comment]
This one can be closed, was done in https://github.com/etix/mirrorbits/pull/169

**Comment by lazka** [comment]
it's not merged yet :)

**Comment by elboulangero** [comment]
Indeed, sorry for the confusion

**Comment by jbkempf** [comment]
#169 is now merged.
