### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by dduportal** [etix/mirrorbits#138]
Hello there, I'm working for the Jenkins Infrastructure project which uses mirrorbits for its download infrastructure.

We are wondering if this project is still maintained and if it would need help for this!

As proposed by my predecessor @olblak in #101 and #109 , we could give back some pieces of code such as official Dockerfile, helm chart and some time to help (and a bit of experience in golang around the updatecli project created by Olivier).

**Comment by jbkempf** [comment]
Yes, it is maintained, but not too actively. I check if there is anything important, and sometimes merge them.

@etix is busy as hell though :)

I thought I answered to @olblak but maybe I did not ;)

**Comment by dduportal** [comment]
Thanks for the anwser @jbkempf!

As a matter of fact you did answer to Olivier: https://github.com/etix/mirrorbits/issues/101#issuecomment-602628235 :), but it was 3 years ago.


A few contributions I would expect to propose if the maintainers are open for it (on the principle but also on the time):

- Enable CI with GitHub actions (I see there is a TravisCI file but https://github.blog/2022-04-15-security-alert-stolen-oauth-user-tokens/) to provide a feedback loop to any contributor (and to the project itself)
- Proposing a reworked Docker image following good practises in production (for instance: no Golang installation) with multistage build
- Updating the Golang version (and eventually dependencies)
- Proposing a Kubernetes Helm Chart

WDYT?

**Comment by jbkempf** [comment]
All good ideas for me.

**Comment by Jehan** [comment]
@jbkempf While we are at it, since this report seems to be a generic report about maintenance, any chance that #128 could be looked at and merged in eventually as well?

You said my patch looked good a year ago. Then I improved it further after some code review.

I'd really love for this to get in so that GNOME (which uses it for our downloads of GIMP) could update eventually on their infrastructure (after a version release, I guess?) so that we finally get usable download stats.
Thanks! 💌

**Comment by jbkempf** [comment]
> @jbkempf While we are at it, since this report seems to be a generic report about maintenance, any chance that #128 could be looked at and merged in eventually as well?

Yes, trying to get this project under my name right now, for this.

**Comment by olblak** [comment]
> Yes, trying to get this project under my name right now, for this.

Wouldn't it be better to create a new GitHub organisation?
 
Mirrorbits is a nice project and I see strong interest from different large OSS project.
So we could have maintainers from those different organisation

**Comment by dduportal** [comment]
> > Yes, trying to get this project under my name right now, for this.
> 
> Wouldn't it be better to create a new GitHub organisation?
> 
> Mirrorbits is a nice project and I see strong interest from different large OSS project. So we could have maintainers from those different organisation
> 
> Btw I still have access to mirrorbits on DockerHub https://hub.docker.com/orgs/mirrorbits

Excellent idea!

**Comment by olblak** [comment]
I would be more than happy to help with this.
If it's a solution that interest @etix and @jbkempf
This repository could be transferred to a specific GitHub organization.

The Jenkins project started using Mirrorbits several years ago , 

More people with merge permission means less burden on the few maintainers and in this case that could benefit other large OSS project too

**Comment by benoit74** [comment]
Transforming the project to a community managed project is definitely something which makes sense to me. And I'm sure that as a Kiwix developer, I would have time to contribute if we decide to move to mirrorbits, since we have some needed features which are missing in mirrorbits.

However, I'm sure that the most difficult part is not the technical one (creating an organization and moving code there is easy, we could even fork it there if needed, even if I would prefer not) but the governance part (who is a maintainer, who can vet in/out maintainers, how maintainers decide what is acceptable to be merged or not, ...). 

But moving to this is probably a journey and knowing that this journey is moving on is already a great achievement, I don't think that we need everything to be settled to start moving.

**Comment by elboulangero** [comment]
It's very likely that we'll use mirrorbits for Kali Linux. We aim at having it in prod in the coming months. I'll be happy to help maintaining it as well, when time allows.

**Comment by jbkempf** [comment]
Thanks a lot for the suggestions, I’m working on that issue to have more shared development on this project.

I’m a bit busy with conferences at the moment, but I have not forgotten.

**Comment by jbkempf** [comment]
I have now the control of the repository :)

Please rebase your things :)

**Comment by lemeurherve** [comment]
Fantastic news!

I suppose creating a release with the current pending changes https://github.com/etix/mirrorbits/compare/v0.5.1...master is planned?

This message serves additionally as an excuse to also propose my help.

**Comment by jbkempf** [comment]
Ongoing work on several MR, reading the backlog and all. Please rebase your work :D

Release end of this year.

**Comment by jbkempf** [comment]
Just FYI, I did apply a lot of MR, fixing a lot of bugs, and answered many questions.

**Comment by dduportal** [comment]
> Just FYI, I did apply a lot of MR, fixing a lot of bugs, and answered many questions.

Thanks! Do you plan to release a new version with all the changes soon?

**Comment by jbkempf** [comment]
v0.6.0 was just released!

**Comment by dduportal** [comment]
> v0.6.0 was just released!

Thanks!

The changelog mentions it is a major release but it looks like it is a minor release (0.5.x -> 0.6.y): I assume we should test carefully and expect breaking changes?

**Comment by dduportal** [comment]
> We never did a 1.0.x, so yes, this is major.
> 
> And yes, be extra careful, it's the first release in 6 years, with many new features.


0.5 to 0.6 seems to convey a "minor" (at least in semver) change for consumers, that's why I was asking.

But we agree: 6 years without a release clearly requires caution ;) Thanks again

**Comment by jbkempf** [comment]
> > We never did a 1.0.x, so yes, this is major.
> > And yes, be extra careful, it's the first release in 6 years, with many new features.
> 
> 0.5 to 0.6 seems to convey a "minor" (at least in semver) change for consumers, that's why I was asking.

We're not using semver.
