### ISSUE TITLE
add md5 repsonse for file requests

### ISSUE THREAD

**Issue by MartijnKaijser** [etix/mirrorbits#14]
In mirrorbrain there was an option that each listed file could be called with an added ".md5" which returned the hash stored in the database
Example:
"http://mirrors.kodi.tv/addons/gotham/metadata.themoviedb.org/metadata.themoviedb.org-3.8.4.zip.md5"

Storing the hash is already added in https://github.com/etix/mirrorbits/commit/e566e933d1302e30fe26fc3f0acb5cf921c5ee83

Proposal:
add a handler like ?mirrorlist that will provide a template like mirrorlist.html to give us the md5 that is already in the db

**Comment by etix** [comment]
As you mentioned, you can already get it in the same API call as the mirror URL, file size and so on.
I guess you need it for verifying the downloaded archive from the client side? If not, what is your use-case?

**Comment by MartijnKaijser** [comment]
Yes it's for verifying from client side of the downloaded .zip 
Additionally we use it to see if our addons.xml (add-on repository list) has changed by comparing stored md5 and md5 on the server. If mismatch it means the list has been updated and we fetch the complete xml.

**Comment by etix** [comment]
I'm still wondering if ?md5 wouldn't be better than .md5, any strong preference on your side?

**Comment by kib** [comment]
Our client currently requests .md5 but I could rewrite that with nginx

**Comment by MartijnKaijser** [comment]
and we could also alter it to ? on client side for future versions. Perhaps some param in our repo addon

**Comment by etix** [comment]
I've implemented it as query argument, I let you guys test and confirm it works as expected.

**Comment by MartijnKaijser** [comment]
Seems to work just fine right @kib?

**Comment by kib** [comment]
Yes, I simply added a redirection in the location block that does the reverse proxy like so:

     rewrite ^(.*)\.md5$ $1?md5? last;

Requests are properly rewritten and the clients are happy.

**Comment by etix** [comment]
Excellent! I guess I can close this ticket, reopen if needed.

**Comment by MartijnKaijser** [comment]
thx for the quick fix.
Our mirror system is loving it a lot :)

**Comment by kib** [comment]
This also adds the long term request that was added in #4
