### ISSUE TITLE
monitor loop causing excessive disk read

### ISSUE THREAD

**Issue by kib** [etix/mirrorbits#18]
The monitor loop 

    -monitor=true 

seems to be scanning all files on disk by reading the full file, then waiting 5 minutes and starting over again. We are seeing continuous 50-100 MB/sec disk read.

It seems (or so i am told by people smarter than me) that this could be implemented by using the linux inotify system for any loops after the first one. inotify is supported in go it seems. 
That way mirrorbits would be notified of filesystem changes in the folder, and could selectively add files / hash them.

For now we have had to disable the monitor loop and manually set up crontabs. However this feels cludgy. :)

**Comment by kib** [comment]
![graph](https://cloud.githubusercontent.com/assets/2970526/9009247/3ec457c8-37a0-11e5-9680-c3f42923595b.png)

**Comment by kib** [comment]
For Kodi we use a fasthash algorithm that combines the foldernames / mtimes and hashes that into the database. We then only have to check that to see whether anything has changed. It significantly speeds up checking initially.

It can be found here: https://github.com/xbmc/xbmc/blob/master/xbmc/video/VideoInfoScanner.cpp#L1780

**Comment by etix** [comment]
Indeed if the files change a lot, they will get re-hashed very often, causing a non negligible load on the disk. First ensure that you disabled non-used hash algorithm: `SHA1: false, SHA256: false, MD5: true`.

inotify will probably not help much since only modified files are rehashed by mirrorbits. Every 5 minutes it will check which files were modified and rehash them. Using *notify will trigger a hash as soon as a file is changed on disk which might increase the load if some files are changing more often than the mirrorbits 5 minutes range.

You should also note that by disabling the monitor you also stop polling mirrors so if a mirror goes down it won't be noticed and some client will end up there.

**Comment by kib** [comment]
99% of files never change.
It seems we have a bug then.

**Comment by etix** [comment]
I'm going to add an option to the config to change the duration between hashing so you can disable it without disabling the monitoring of the mirrors.

**Comment by kib** [comment]
I rather understand why mirrorbits keeps reading from disk. I am pretty sure it is hashing items that are already hashed

**Comment by etix** [comment]
Then it's a bug no-one ever reported. I'm going to investigate.

**Comment by kib** [comment]
I am currently running a refresh manually. I am pretty sure it will complete eventually
After it finishes I will restart the main process with monitor=true. I would expect to see no/hardly any disk activity

**Comment by etix** [comment]
How long does it take to hash the whole repository?

**Comment by etix** [comment]
Just guessing but do you have symbolic links that can cause a loop?

**Comment by etix** [comment]
After reviewing the code the only options to re-trigger a scan are:
- file size change
- file modification time change
- hashing configuration change
- mountpoints loop

```Go
rehash := (GetConfig().Hashes.SHA1 && len(sha1) == 0) ||
		(GetConfig().Hashes.SHA256 && len(sha256) == 0) ||
		(GetConfig().Hashes.MD5 && len(md5) == 0)

if rehash || size != d.size || modTime != d.modTime {
	...
}
```

**Comment by wsnipex** [comment]
we're not sure the IO load is coming from hashing, it might just be the constant scan/repository crawling.
If its this, it should be much better with the adjustable interval now.

With inotify the local repository scan would not be needed at all, part from at startup.

ps: thanks for this great software :)

**Comment by kib** [comment]
This is what disk throughput looks like when I run the scan every few hours.
I haven't added any files to the repository and as far as I know we do not have any mountpoints or hardlinks present anywhere in our repository.

![disk_throughput](https://cloud.githubusercontent.com/assets/2970526/9021582/aa705d7e-3849-11e5-8c30-35f3a166f220.png)

What could I do to troubleshoot this further ?

**Comment by etix** [comment]
As a comparison this is what the disk throughput looks like on our production cluster at VideoLAN.

![image](https://cloud.githubusercontent.com/assets/38853/9022019/ad25b400-3863-11e5-9104-92d7c3fd4fc8.png)

Do you run a redis node on the same server? If yes, it's probably caused by redis when writing the rdb file during a scan. A scan of the mirrors or the local file system creates a lot of changes in the database. For instance, the approximate number of keys that are modified after a complete scan are `number of files served × number of mirrors`.

Few tips to tweak:
- http://redis.io/topics/admin
- Increasing the time between subsequent write to disk (like `save 300 50000`)

**Comment by kib** [comment]
It must be that issue, we have about 13000 files and 39 mirrors. I will make those changes, thanks for the advice.

**Comment by etix** [comment]
So the process `redis-rdb-bgsave` is not responsible for this increased load? Can you share your iotop output please?

I just checked on get.videolan.org and I can barely see mirrorbits in the iotop output and we have about 10148 files and 80 mirrors.

**Comment by kib** [comment]
I just ran this

    mirrorbits -debug=true refresh 

And end up with this:

    scan.go:260         2015/08/01 14:17:15.218 UTC /addons/dharma/skin.back-row/skin.back-row-3.2.7.zip: MD5 197ed19e7f48ce833999d25d6963d538
    scan.go:260         2015/08/01 14:17:15.218 UTC /addons/dharma/skin.carmichael/addon.xml: MD5 6a0ed52b98ad46fce59b926e503b8c14
    scan.go:260         2015/08/01 14:17:15.218 UTC /addons/dharma/skin.carmichael/changelog-1.0.0.txt: MD5 1c8b76d1a2e1e48f5d0c99e1b7249a13
    scan.go:260         2015/08/01 14:17:15.219 UTC /addons/dharma/skin.carmichael/icon.png: MD5 cbf71cc359d6a5529da5ffff8825be35

If that scan.go:260 refers to https://github.com/etix/mirrorbits/blob/master/scan.go#L260 then it is clearly rehashing for some weird reason.

**Comment by kib** [comment]
I just ran it again and stopped around the same time:
    scan.go:260         2015/08/01 14:31:25.915 UTC /addons/dharma/skin.back-row/skin.back-row-3.2.7.zip: MD5 197ed19e7f48ce833999d25d6963d538

It happily creates the same MD5 again...

**Comment by kib** [comment]
Ah disregard that, it is not rehashing, I read the code wrong.

**Comment by etix** [comment]
Yes it is. This line is printed just after rehashing.
https://github.com/etix/mirrorbits/blob/master/scan.go#L246

**Comment by kib** [comment]
Yeah i manage to read the code wrong twice :)

**Comment by wsnipex** [comment]
I captured this on iotop by coincidence:
>14:30:50  2446 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % redis-server *:6379
14:30:50  6610 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % grep --colour=auto -E mirrorbits|redis
14:30:53  6398 be/4 mirrorbi   73.71 M/s    0.00 B/s  0.00 %  4.62 % mirrorbits -debug=true refresh
14:30:53 17523 ?dif mirrorbi    0.00 B/s  123.07 K/s  0.00 %  0.07 % mirrorbits -D=true -config=/home/mirrorbits/mirrorbits.conf -monitor=true -p=/home/mirrorbits/mb.pid
14:30:53  2446 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % redis-server *:6379
14:30:56  6398 be/4 mirrorbi   47.72 M/s    0.00 B/s  0.00 %  5.87 % mirrorbits -debug=true refresh
14:30:56 17523 ?dif mirrorbi    0.00 B/s  119.11 K/s  0.00 %  0.06 % mirrorbits -D=true -config=/home/mirrorbits/mirrorbits.conf -monitor=true -p=/home/mirrorbits/mb.pid
14:30:56  2446 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % redis-server *:6379
14:30:59  6398 be/4 mirrorbi   63.96 M/s    0.00 B/s  0.00 %  5.08 % mirrorbits -debug=true refresh
14:30:59 17523 ?dif mirrorbi    0.00 B/s  121.94 K/s  0.00 %  0.00 % mirrorbits -D=true -config=/home/mirrorbits/mirrorbits.conf -monitor=true -p=/home/mirrorbits/mb.pid
14:30:59  2446 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % redis-server *:6379
14:31:02  6398 be/4 mirrorbi   49.41 M/s    0.00 B/s  0.00 %  5.91 % mirrorbits -debug=true refresh
14:31:02 17523 ?dif mirrorbi    0.00 B/s  112.97 K/s  0.00 %  0.07 % mirrorbits -D=true -config=/home/mirrorbits/mirrorbits.conf -monitor=true -p=/home/mirrorbits/mb.pid
14:31:02  2446 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % redis-server *:6379
14:31:02  6610 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % grep --colour=auto -E mirrorbits|redis
14:31:05  6398 be/4 mirrorbi   57.44 M/s    0.00 B/s  0.00 %  5.35 % mirrorbits -debug=true refresh
14:31:05 17523 ?dif mirrorbi    0.00 B/s  116.64 K/s  0.00 %  0.00 % mirrorbits -D=true -config=/home/mirrorbits/mirrorbits.conf -monitor=true -p=/home/mirrorbits/mb.pid
14:31:05  2446 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % redis-server *:6379
14:31:08  6398 be/4 mirrorbi   84.07 M/s    0.00 B/s  0.00 %  4.11 % mirrorbits -debug=true refresh
14:31:08 17523 ?dif mirrorbi    0.00 B/s  104.86 K/s  0.00 %  0.06 % mirrorbits -D=true -config=/home/mirrorbits/mirrorbits.conf -monitor=true -p=/home/mirrorbits/mb.pid

**Comment by wsnipex** [comment]
for reference, this file didn't change in a long time:
>ll /var/www/downloads/addons/dharma/skin.back-row/skin.back-row-3.2.7.zip
-rw-r--r-- 1 git addons 49743792 Dec 15  2013 /var/www/downloads/addons/dharma/skin.back-row/skin.back-row-3.2.7.zip
dharma ~ # md5sum /var/www/downloads/addons/dharma/skin.back-row/skin.back-row-3.2.7.zip
197ed19e7f48ce833999d25d6963d538  /var/www/downloads/addons/dharma/skin.back-row/skin.back-row-3.2.7.zip

**Comment by kib** [comment]
wsnipex read above please :)

**Comment by etix** [comment]
Can you please apply this patch a give me a subset of the output?
https://gist.github.com/etix/3a0e13be9a5b7f6a53ee

**Comment by kib** [comment]
@etix I am more than willing to insert some debugging lines into that code block and reinstall / upgrade / run refresh just to see what is going on. - but i can't write them

**Comment by kib** [comment]
@etix thanks!, give me a sec

**Comment by kib** [comment]
They are all saying modtime is changed
    2015/08/01 14:49:58.577 UTC rehash: false | size: false | modTime: true

**Comment by kib** [comment]
Is it possible something goes wrong with timezones when adding to redis ?

**Comment by kib** [comment]
redis is running as root (i am pretty sure that is not best practice, but i must have done that wrong when i set it up half a year ago)
mirrorbits is running as user mirrorbits

the locale and timezone settings are as follows:

```
# whoami
root
# locale
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
# date +%Z
UTC
# su mirrorbrain -
$ date +%Z
UTC
$ locale
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

**Comment by wsnipex** [comment]
is it possible that the scanner only looks at the top level Repository dir:
drwxrwxr-x 11 mirrorbrain www-data 4096 Aug  1 15:05 /var/www/downloads/

since this _has_ been modified

**Comment by etix** [comment]
Can you please test this new revision of the patch?
https://gist.github.com/etix/3a0e13be9a5b7f6a53ee

**Comment by etix** [comment]
Directories modification time aren't checked. We care only about files so this cannot be the reason. Same for Redis, we store dates as string including the timezone and DST to avoid most timezone issues but it seems there's still something wrong :)

**Comment by kib** [comment]
```
scan.go:253         2015/08/01 15:28:47.831 UTC rehash: false | size: false | modTime: true
scan.go:268         2015/08/01 15:28:47.837 UTC /addons/dharma/skin.back-row/changelog-3.2.7.txt: MD5 131b7424c69ec328eafbbc02d689ec08
scan.go:253         2015/08/01 15:28:47.837 UTC rehash: false | size: false | modTime: true
scan.go:268         2015/08/01 15:28:47.845 UTC /addons/dharma/skin.back-row/icon.png: MD5 b4848e87111d8ce0ee7697d0f3610c3a
scan.go:243         2015/08/01 15:28:47.845 UTC modTime from fileInfo: 2013-12-15 10:22:57 +0000 UTC
scan.go:244         2015/08/01 15:28:47.846 UTC modTime from redis: 2013-12-15 10:22:57 +0000 UTC
scan.go:245         2015/08/01 15:28:47.846 UTC modTime parsed: 2013-12-15 10:22:57 +0000 UTC
scan.go:253         2015/08/01 15:28:47.846 UTC rehash: false | size: false | modTime: true
scan.go:268         2015/08/01 15:28:48.341 UTC /addons/dharma/skin.back-row/skin.back-row-3.2.7.zip: MD5 197ed19e7f48ce833999d25d6963d538
scan.go:253         2015/08/01 15:28:48.341 UTC rehash: false | size: false | modTime: true
scan.go:268         2015/08/01 15:28:48.342 UTC /addons/dharma/skin.carmichael/addon.xml: MD5 6a0ed52b98ad46fce59b926e503b8c14
```

**Comment by kib** [comment]
i think there is a typo in the last one, you did e.path there

**Comment by kib** [comment]
Or wait, do i need to refresh the entire repo now to wait until it writes them back to redis ?

**Comment by etix** [comment]
No the last one is good but I don't see it, we should see a `modTime to redis: %s` as well. But anyway, the results you gave back are looking good. Weird.

**Comment by kib** [comment]
Is it possible it is simply not writing it to redis because of something else?

**Comment by etix** [comment]
Yeah, that's my current assumption, but what is weird is that `modTime from redis` is correct. I would have expected it to be empty in this case. It makes no sense...

**Comment by kib** [comment]
hold on, is it saying that the from file and from redis are the same, but the comparison is false, eg modTime != redis.modTime

wut

**Comment by etix** [comment]
I think I caught it, let me send you another patch but I don't know why it would work at all for all of us.

**Comment by kib** [comment]
I'm juist guessing but maybe different version of redis, os, nginx, could be a hundred things

**Comment by etix** [comment]
Before I used modTime != d.modTime but according to the documentation:
>Equal reports whether t and u represent the same time instant. Two times can be equal even if they are in different locations. For example, 6:00 +0200 CEST and 4:00 UTC are Equal. This comparison is different from using t == u, which also compares the locations.

Please apply this revision:
https://gist.github.com/etix/3a0e13be9a5b7f6a53ee

**Comment by kib** [comment]
I already reverted your previous diff and was lazy so I just took the one compare change and manually added it.

Now this happens when i refresh:
```
mirrorbits@dharma:~$ mirrorbits -debug=true refresh
redis.go:150        2015/08/01 15:46:24.851 UTC No redis master available, trying using the configured RedisAddress as fallback
redis.go:208        2015/08/01 15:46:24.851 UTC Connected to redis master 127.0.0.1:6379
scan.go:298         2015/08/01 15:46:24.852 UTC [source] Scanning the filesystem...
scan.go:306         2015/08/01 15:46:28.411 UTC [source] Indexing the files...
scan.go:361         2015/08/01 15:46:28.798 UTC [source] Scanned 12233 files
```

I then added one new file in a subdirectory somewhere
```
mirrorbits@dharma:~$ mirrorbits -debug=true refresh
redis.go:150        2015/08/01 15:49:07.429 UTC No redis master available, trying using the configured RedisAddress as fallback
redis.go:208        2015/08/01 15:49:07.429 UTC Connected to redis master 127.0.0.1:6379
scan.go:298         2015/08/01 15:49:07.429 UTC [source] Scanning the filesystem...
scan.go:260         2015/08/01 15:49:09.779 UTC /addons/jarvis/test.txt: MD5 efbba249bd50cd2e9983a73f1af2bab7
scan.go:306         2015/08/01 15:49:10.869 UTC [source] Indexing the files...
scan.go:361         2015/08/01 15:49:11.263 UTC [source] Scanned 12234 files
```

It now takes about 10 seconds...

nice work :+1:

**Comment by etix** [comment]
Awesome! Let me clean this code and push a fix.

**Comment by wsnipex** [comment]
yay, nice.
Go has some strange syntax though :)

**Comment by kib** [comment]
```
~$ time mirrorbits -debug=true refresh
redis.go:150        2015/08/01 16:07:19.574 UTC No redis master available, trying using the configured RedisAddress as fallback
redis.go:208        2015/08/01 16:07:19.575 UTC Connected to redis master 127.0.0.1:6379
scan.go:298         2015/08/01 16:07:19.575 UTC [source] Scanning the filesystem...
scan.go:306         2015/08/01 16:07:22.905 UTC [source] Indexing the files...
scan.go:361         2015/08/01 16:07:23.301 UTC [source] Scanned 12233 files

real    0m3.742s
user    0m1.856s
sys     0m1.648s
```

**Comment by etix** [comment]
Scanning 12233 files in less than 4 seconds looks way better to me! Fix is on its way.

**Comment by etix** [comment]
If the fix works as expected, don't forget to restore RepositoryScanInterval. 5 minutes is probably a sane default for you as well since it only takes few seconds (when this bug is not kicking around ;)).

**Comment by kib** [comment]
Yep, I did that already!
Thanks again.
