### ISSUE TITLE
Impossible to edit mirror when name is subset of other mirror

### ISSUE THREAD

**Issue by kib** [etix/mirrorbits#19]
When there are two mirrors with very similar names the show command will fuzzy logic list both mirrors, in my opinion this is a good thing.

The issue however is threefold:
- The edit command will do the same, and does not use strict checking
- There is no way (I found) to change the descriptive name of a mirror
- (SOLVED) It is impossible to add a mirror with the same name as one that was previously removed. 

**Example:**

First I add a few mirrors called *test.example.com* and *secondtest.example.com*

    $ mirrorbits add -http="http://test.example.com" test.example.com 
    Warning: unable to guess the geographic location of test.example.com
    Mirror added successfull
    $ mirrorbits add -http="http://secondtest.example.com" secondtest.example.com
    Warning: unable to guess the geographic location of test.example.com
    Mirror added successfull
It is clear this worked from the output of the show command

    $ mirrorbits show example
    secondtest.example.com
    test.example.com
But I can't edit *test.example.com*

    $ mirrorbits edit test.example.com
    secondtest.example.com
    test.example.com
I proceed to remove *secondtest.example.com* so i can edit *test.example.com*

    $ mirrorbits remove secondtest.example.com
    Mirror removed successfully
    $ mirrorbits edit test.example.com
I then find out I can't edit the displayname of this mirror. 
I end up removing it completely and recreating it with the new displayname

When I tried this previously I also was not able to recreate the same mirrorname, it complains the mirror already exists:

    $ mirrorbits add <lots of info> z.os6.org
    Mirror z.os6.org already exists!
    $ mirrorbits edit z.os6.org
    No match for z.os6.org

**Comment by kib** [comment]
Edit on the last issue, this seems to be created with a previous version of mirrorbits, there was a MIRROR_z.os6.org key left in the redis database with no other keys / keydata with it. I've manually removed the offending key and was able to reuse the name.

**Comment by kib** [comment]
The naming issue also affects removing mirrors:
    
    $ mirrorbits remove test.example.com
    secondtest.example.com
    test.example.com
    $ mirrorbits remove secondtest.example.com
    Mirror removed successfully

**Comment by etix** [comment]
Nice catch! Thanks a lot :)

**Comment by kib** [comment]
just 'lucky' we had two similar names I guess. Thanks for the quick fix :+1:

**Comment by kib** [comment]
Any chance you could make it possible to change the descriptive name of the mirror ?

**Comment by etix** [comment]
Renaming a mirror is quite difficult currently since the mirror identifier is part of thousands of keys in the database. It would require to disable the mirror, replace all matching keys and take it back online. Another option would be to use an intermediate table but that would require a breaking database format change. Your best option here is to remove and add the mirror back but with a different name.

**Comment by kib** [comment]
@etix I see, well than we just must be careful not to make mistakes :+1:

**Comment by etix** [comment]
It's definitely on my TODO-breaking list, I just want to do all breaking changes at the same time, most certainly just before 1.0-stable.

**Comment by kib** [comment]
patch for editing names confirmed working, just tested adding a mirror with subsetname, was able to edit and remove it no problem.
