### ISSUE TITLE
mirrorlist: piegraph broken after recent change

### ISSUE THREAD

**Issue by kib** [etix/mirrorbits#21]
Changing the weight from int to string in https://github.com/etix/mirrorbits/commit/048833def0d7c2d1dae2d3bea1c2e6ac77e9a538 breaks the piegraph in the mirrorlist.

See comment at https://github.com/etix/mirrorbits/commit/048833def0d7c2d1dae2d3bea1c2e6ac77e9a538#commitcomment-12490100

**Comment by kib** [comment]
I'm rewriting that part in the mirrorlist.html to use the newer API from google, PR for that will be incoming soon.

**Comment by etix** [comment]
My implementation is bad, it should be up to the template to decide what do display in this case. I will probably return a float directly. I just suspect that formatting the float's precision in the templates is not possible.
