### ISSUE TITLE
Multiple IP adresses: no ASN so no proper balancing

### ISSUE THREAD

**Issue by kib** [etix/mirrorbits#23]
When connecting from mobile devices mirrorbits 'sees' two external IP's for the device, and is unable to select an ASN. The result is that the client does not receive a download at optimal speed.

For example: http://up.kibje.com/20150803/Screenshot_2015-08-03-17-27-09.png
I have IP's 212.67.184.99 (ASN8608) and 66.249.81.223 (ASN15169)

For mobile the first address almost always corresponds to the location-defining IP of the client. In my case when I am on WLAN I get the proxy of my location, when I am not on WLAN I get the proxy address of my mobile phone provider.
The second IP address is caused by mobile browser optimization services (eg Google / Akamai / Apple) which most phone manufacturers are using on their OS's these days. They can also be caused by webpage filtering software but that is less common.

In my opinion the first address should always be selected if two or more addresses are available.

**Comment by etix** [comment]
In the current implementation, the X-Forwarded-For header is expected to contain only one IP address. How were you able to get two?

**Comment by etix** [comment]
> In my opinion the first address should always be selected if two or more addresses are available.

The first is the "real" user's location but since we need to feed the proxy instead, shouldn't we use the last one? In case of a browser optimization services then it's probably best to use the first, since binary files will probably not go through the proxy.

**Comment by kib** [comment]
I'll leave that design choice op to you, but picking either is likely better than none.
