### ISSUE TITLE
to-do: add method for reloading GeoIP database

### ISSUE THREAD

**Issue by MartijnKaijser** [etix/mirrorbits#30]
From the looks of it it's not possible (or easy) to (re)load the new GeoIP database.

**Comment by MartijnKaijser** [comment]
What also seems missing is a method mirrorbrain had for updating the GeoIP data of the already added mirror.
     mb update -A --all-mirrors

Could be that i missed this and it's already done automatic

**Comment by wsnipex** [comment]
its not properly tested, but something like https://github.com/wsnipex/mirrorbits/commit/03f3e0a6f45ca467803185b358bfb544d89717dc might work.

**Comment by etix** [comment]
Indeed this should work. But the official geoip library is supposed to already support that (built-in autoreload) but I've never been able to make it work until now. I don't know if it's related to the library itself or the go wrapper. We'll have to dig a bit more into it before adding a workaround I think.
