### ISSUE TITLE
Connect to specific redis database index

### ISSUE THREAD

**Issue by ashledombos** [etix/mirrorbits#32]
Hi :)

I'm wanting to use mirrorbits on a machine that already runs redis. So the database "0" is already in use. In mirrorbits.conf I can see:

    RedisAddress: 127.0.0.1:6379
    RedisPassword:

but I don't see a parameter to connect to another database than DB 0; 

Is there a way to change the database index used by mirrorbits?

Raphaël

**Comment by etix** [comment]
This is not yet implemented sorry. I'm a bit overwhelmed these days so I cannot give you an ETA, but it shouldn't be hard to do if you want to give it a try.

**Comment by ashledombos** [comment]
Thanks for the reply etix, and I understand you can't give any ETA. Unfortunately I don't have yet the skills for it. I'll find another way then… Is it possible to turn this post as a feature request? If not then just close it please :)

**Comment by etix** [comment]
Sure, I'll add support for it ASAP.
