### ISSUE TITLE
crash in askRole

### ISSUE THREAD

**Issue by poempelfox** [etix/mirrorbits#33]
Trying to run this (current git checkout) on Ubuntu 14.04, with sentinel disabled, every command crashes as follows:
```
panic: runtime error: index out of range

goroutine 1 [running]:
main.(*redisobj).askRole(0xc208038c40, 0x7f10d8e8f5b8, 0xc20805d220, 0x0, 0x0, 0x0, 0x0)
        /home/mirrorbits/src/github.com/etix/mirrorbits/redis.go:184 +0x180
main.(*redisobj).connect(0xc208038c40, 0x0, 0x0, 0x0, 0x0)
        /home/mirrorbits/src/github.com/etix/mirrorbits/redis.go:161 +0x360
main.(*cli).CmdAdd(0xcb4bd0, 0xc20800a020, 0x4, 0x4, 0x0, 0x0)
        /home/mirrorbits/src/github.com/etix/mirrorbits/commands.go:269 +0xc25
```
Commenting out the `role, err := r.askRole(c)` on line 161 (and the following ifs) makes it run without crashing.

**Comment by etix** [comment]
Are you sure you're running Redis 2.8.12 or later? Previous versions are not supported.

**Comment by etix** [comment]
Closing, please re-open if the problem still occurs.
