### ISSUE TITLE
Make it possible to exclude some files / always send them to fallback

### ISSUE THREAD

**Issue by samnazarko** [etix/mirrorbits#36]
We are hosting an APT repository with pdiffs, and I noticed Mirrorbit's scan feature uses file sizes to check file integrity.

The Index file on an APT repository may not change in size when it is updated. 

If you look at http://realtime.mirror.osmc.tv//osmc/apt/dists/jessie-devel/main/binary-armhf/Packages.diff/Index, you will see that the current checksum is stored as are a few previous ones. But this file never grows in size as checksums are simply replaced. This can give a 'Hash Sum Mismatch' error when running apt-get update.

It would be great if we could use a fallback specified in the mirrorbits.conf for certain paths or filenames.

**Comment by wsnipex** [comment]
https://github.com/etix/mirrorbits/pull/27/ would probably fix the issue, since it detects every file change, even if size doesn't change.

**Comment by samnazarko** [comment]
I'll try it, but not sure if this will work, as I think Mirrorbits only checks the file size on rsync. I am scanning the local repo every 2 minutes but it still doesn't mark the files as invalid on old mirrors, even though the access time has changed.

For now, I will concatenate a random # of bytes to the file when it is generated by the pdiff script

On 22 Jan 2016, at 18:08, Wolfgang Schupp <notifications@github.com<mailto:notifications@github.com>> wrote:


#27<https://github.com/etix/mirrorbits/pull/27> would probably fix the issue, since it detects every file change, even if size doesn't change.

-

**Comment by kib** [comment]
Let's hope your last random is not the same as your current random then :+1:

**Comment by samnazarko** [comment]
Yes, I was reading from urandom.

But I spoke to etix and he said it also checks last access time as well as file size. I had a shared mount between the file server and the Mirrorbits server. The time zone was wrong. After fixing that things are working as expected, so we can consider this a non issue
