### ISSUE TITLE
Add configure to define the amount of backup mirror locations are returned

### ISSUE THREAD

**Issue by MartijnKaijser** [etix/mirrorbits#39]
Currently several back up locations are added to the response next to the main redirect. Since not all software actually use or needs the extra locations it would be great if this could be configured to the "needed" amount.
This should greatly reduce traffic from our server.

**Comment by wsnipex** [comment]
see https://github.com/wsnipex/mirrorbits/commit/6ca75e229345b1c2530bc40e6c8dd3c0e0b02ddd
this is already live on kodi's mirrorbits.

By my estimate we save around 1-6 kb/request depending on the clients location. This amounts to several hundred MB per minute with our average 5,5k reqs/sec.
@etix interested in a PR?

**Comment by etix** [comment]
Hello @MartijnKaijser and @wsnipex,

I would definitely be interested by a PR.
