### ISSUE TITLE
mirrorlist: google maps API requires an API key

### ISSUE THREAD

**Issue by zifnab06** [etix/mirrorbits#44]
Google Maps returns "The Google Maps API server rejected your request. This service requires an API key.". 

According to https://stackoverflow.com/questions/38462525/google-maps-static-api-is-asking-for-api-key, all new servers online after June 22nd 2016 require an API key. 

I don't know if adding an API key is feasible or not, due to restrictions from google on number of requested maps per day, or if it would be better to look at implementing a different provider. 

(I'm willing to do either in a PR)

**Comment by MartijnKaijser** [comment]
I'm sure adding a configuration field for the key should be fine.

**Comment by etix** [comment]
Exactly, adding the API key to the configuration file should be the way to go. In the long term, I'm in favor of supporting other maps backend like OSS but that's not very high priority.
