### ISSUE TITLE
Files in symlinked folder not found on mirror

### ISSUE THREAD

**Issue by manno** [etix/mirrorbits#45]
For historical reasons we have some symlinked folders, like "2016 -> 33c3".

Files in the symlinked location are reported as "not present on any mirror" and served by our fallbacks.

* https://cdn.media.ccc.de/congress/2016/h264-hd/33c3-7811-deu-Irren_ist_staatlich.mp4?mirrorlist
* https://cdn.media.ccc.de/congress/33c3/h264-hd/33c3-7811-deu-Irren_ist_staatlich.mp4?mirrorlist

**Comment by etix** [comment]
Indeed, this should be supported. I don't know what is required to make it work but I'll see what I can do.

**Comment by etix** [comment]
Please test the latest master and report back if it works as expected.

Note: I've also added a new configuration field for the Google Maps API key, [see here](https://github.com/etix/mirrorbits/commit/1d85a64a23361747f80700c776ed282061f1a971).

**Comment by manno** [comment]
Thanks, looks great!
