### ISSUE TITLE
Allow renaming a mirror

### ISSUE THREAD

**Issue by etix** [etix/mirrorbits#50]
A mirror, once added cannot be renamed. We need a way to change that without causing too much trouble within a cluster.

**Comment by MartijnKaijser** [comment]
Just came accross this when a mirror requested a name change. Not a big deal to create a new one and remove the old but rename would be nice (if only fix a typo)

**Comment by etix** [comment]
Changing the name of a mirror requires a Redis migration since many keys contain the ID of the mirror within their name. Of course we need to introduce a mapping instead and a tool to handle live migrations so we don't disturb production environments.

**Comment by MartijnKaijser** [comment]
For us it wasn't an issue cause we have many mirrors so temporary "loosing" one doesn't hurt our infra. It might not be worth the trouble in the end to introduce a rename option as re-adding the mirror is just a two minute job

**Comment by etix** [comment]
But you may want to keep some of the stats (like the number of downloads) between name change. But yes indeed, as a temporary solution you can totally remove and re-add a mirror.

**Comment by MartijnKaijser** [comment]
Right that would be an issue but we don't really care too much about those being really accurate but others might.
