### ISSUE TITLE
IP database: GeoLite vs. GeoLite2

### ISSUE THREAD

**Issue by MartijnKaijser** [etix/mirrorbits#53]
It seems the GeoLite IP database mirrorbits has been moved to legacy.

Legacy downloads:
http://dev.maxmind.com/geoip/legacy/geolite/

New database downloads:
http://dev.maxmind.com/geoip/geoip2/geolite2/

Perhaps it's better to move to the new v2 version as it seems to be a complete set instead of separate v4 and v6 addresses.
http://dev.maxmind.com/geoip/geoip2/whats-new-in-geoip2/

**Comment by etix** [comment]
This is definitely on my to-do list. I was just not satisfied with the performances of the go libraries I tried 6-8 months ago and I'm a bit concerned about general availability in Linux distributions.

**Comment by oschwald** [comment]
Out of curiosity, which libraries did you test? If you were testing `github.com/oschwald/geoip2-golang`, you may get much better performance using `github.com/oschwald/maxminddb-golang` directly and only reading out the data that you need. The `geoip2` package reads out _all_ the data for the record, which is quite a bit of data. For instance, [reading only the country code](https://github.com/oschwald/maxminddb-golang/blob/master/reader_test.go#L524) takes about 1200 ns on my machine for a random IPv4 lookup.

**Comment by etix** [comment]
Thanks for the input @oschwald. I don't remember which one I tested specifically (I tried 2-3 of them but I wasn't satisfied at the time) but indeed using your "low-level" package seems to be the way to go. I'll do some test against it in the upcoming weeks.
