### ISSUE TITLE
Prevent a mirror from serving a given country

### ISSUE THREAD

**Issue by etix** [etix/mirrorbits#54]
We have one case where a mirror in Russia doesn't allow downloads from Ukrainian users.

**Comment by MartijnKaijser** [comment]
You happen to know which mirror?

**Comment by etix** [comment]
@MartijnKaijser yes, the problem occurred with Yandex but apparently it's the Ukrainian government blocking connections to some (all?) servers in Russia like Yandex.

**Comment by MartijnKaijser** [comment]
We have yandex as well but haven't really heard any issues. I'm sure it happens though

**Comment by etix** [comment]
We only got one report so far but better safe than sorry. If you can, get the latest master and set the following option an all your Russian mirrors: `ExcludedCountryCodes: UA`

**Comment by lazka** [comment]
How can one set ExcludedCountryCodes?

**Comment by etix** [comment]
> How can one set ExcludedCountryCodes?

Use `mirrorbits edit <mirror>` then add the two letter country codes (ISO 3166-2) of the countries you want to exclude for this particular mirror in the `ExcludedCountryCodes` field separated by spaces.

**Comment by lazka** [comment]
ah, thanks!
