### ISSUE TITLE
manual triggered scan doesn't tell if scan was successful or not

### ISSUE THREAD

**Issue by MartijnKaijser** [etix/mirrorbits#56]
When adding a new mirror i always try a manual scan to make sure the scan works. Currently even when the rsync url is wrong there's no cmd line output if it was successful or not.

Perhaps useful to report this on cmd?

**Comment by etix** [comment]
I'm not sure to see what's wrong with the current situation. Can you be more specific?

$ mirrorbits scan somemirror.com

```
2017/06/23 11:02:11.123 CEST Scanning somemirror.com...
2017/06/23 11:02:11.135 CEST [somemirror.com] Requesting file list via rsync...
2017/06/23 11:02:11.169 CEST [somemirror.com] rsync: Error in socket I/O
2017/06/23 11:02:11.169 CEST Scanning somemirror.com failed: rsync: Error in socket I/O
```

$ mirrorbits scan someothermirror.com

```
2017/06/23 11:06:26.622 CEST Scanning someothermirror.com...
2017/06/23 11:06:26.629 CEST [someothermirror.com] Requesting file list via rsync...
2017/06/23 11:06:33.155 CEST [someothermirror.com] Indexed 11196 files (204 known), 0 removed
```

**Comment by MartijnKaijser** [comment]
Those are log lines right?
What i meant is from shell itself you don't get any feedback.

**Comment by etix** [comment]
These are logs but they are printed on stderr so you should have some kind of feedback.

What I did not do is return an error code from the CLI in case the command failed but that will be covered by #57.

**Comment by etix** [comment]
I don't know if you hit a bug or not but in the meantime I'm closing this. Re-open if needed :)
