### ISSUE TITLE
HTTP dynamic header manipulation support

### ISSUE THREAD

**Issue by haneef95** [etix/mirrorbits#66]
Hi,
Can you add support for HTTP dynamic header manipulation? 

This way we can do things like pushing a different filename upon download, using the Content-Disposition HTTP header for example,among other similar things,like optionally pushing file checksum in the header. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition

Thanks,

**Comment by etix** [comment]
This can definitely be done for static headers that applies to all files but I don't see how it can be done dynamically from within mirrorbits.

Even for static headers the easiest way to do it is to proxy mirrorbits with nginx or apache and then add the headers you need. For dynamic headers I recommend using mirrorbits in API mode and handle the logic in your server side app (php, ruby, go or whatever).
