### ISSUE TITLE
Cannot use mirrorbits edit if hash computation is disabled

### ISSUE THREAD

**Issue by poempelfox** [etix/mirrorbits#70]
When one disables all hashing algorithms in the config because they are just not interested in mirrorbits computing them for all files, it becomes impossible to use "mirrorbits edit" to edit mirror settings. The reason is that https://github.com/etix/mirrorbits/blob/1f0ecd93d0da66c6f04349567a2f2396f6c86f51/cli/commands.go#L750 uses filesystem.HashFile() to determine if the temporary file has been modified, and that check always returns true if there are no hashing algorithms enabled.
I think it should still be possible to edit your config even if you do not want to waste CPU and I/O cycles with mirrorbits hashing all files...

**Comment by etix** [comment]
Wow, that was maybe good enough when I wrote that code originally but now it just feel terrible.
