### ISSUE TITLE
http scan

### ISSUE THREAD

**Issue by PalinuroSec** [etix/mirrorbits#77]
Hi, we are migrating the parrotsec.org redirector to mirrorbits and i'm pretty new to this software.
is there any way to scan a mirror without rsync or ftp?

our previous mirror redirector (mirrorbrain) allowed http repositories to be easily (but slowly) scanned via http if no rsync/ftp url was provided

**Comment by etix** [comment]
Hello,

No, we don't support HTTP scanning as a deliberate choice. HTTP scanning is inefficient both for the server and the client. It's also insecure as it doesn't provide any way of validating files with a checksum.

I recommend asking your mirrors to enable either rsync or FTP.
