### ISSUE TITLE
redis alternatives

### ISSUE THREAD

**Issue by PalinuroSec** [etix/mirrorbits#78]
Hello, it's me again.

We tried to configure a little network of distributed redirectors with mirrorbits, but the redis server requires too much ram to hold the whole db for all the mirrors, and we can't perform a ram upgrade on such nodes.

Is it possible to use alternative non-in-memory databases? (what about mongo or postgres)

**Comment by etix** [comment]
Redis only holds the metadata of the files and mirrors in memory. At VideoLAN, with more than 14K files and 100 mirrors we're under 1GB of RAM allocated.

Also we have no plans of supporting any other database right now.

**Comment by PalinuroSec** [comment]
ok thanks, i'll give it another try
