### ISSUE TITLE
Improve web pages

### ISSUE THREAD

**Issue by etix** [etix/mirrorbits#9]
The current implementation of the web pages is not good enough and since I'm not a web guy, any help on this side would be greatly appreciated.

**Comment by BartOtten** [comment]
I hear you. You have an idea already?

**Comment by kib** [comment]
I've made a few small improvements that improve readability a bit. (See http://mirrors.kodi.tv/addons/gotham/addons.xml?mirrorlist )
It would be nice to have the mirrors as direct links to the files but i noticed it is not possible to use the {{.FileInfo.Path}} inside the block that defines the mirrorlist.

Ideally i would like to change 

    <td style="text-align:left">{{$v.HttpURL}}</td>

into something like 

    <td style="text-align:left"><a href="{{$v.HttpURL}}{{.FileInfo.Path}}">{{Mirror}}</a></td>

**Comment by etix** [comment]
There should be a way to access the path. I'll look into it.
I really like your improvements, you should do a pull request!

**Comment by etix** [comment]
@kib see 7de6bf6 and 443308a.

**Comment by kib** [comment]
@etix awesome I've implemented it already (http://mirrors.kodi.tv/addons/isengard/addons.xml?mirrorlist)
